feat-bbio-card-emulation-iso-14443-a-raw-mode
hydrabus/hydrafw_hydranfc_shield_v2 pull request #16
Opened 2020-09-22 22:00 UTC by gvinet

# BBIO card emulation ISO 14443-A - RAW MODE

* From the PPS, we can receive/send raw TPDU command instead of APDUs.
* In a next version, we will add the RATS as well

An example is given in contrib/bbio_hydranfc/bbio_hydranfc_card_emulator_iso_14443_a_raw_example.py

2020-09-23 05:10 UTC, bvernoux requested changes

2020-09-23 05:10 UTC, bvernoux commented on src/hydranfc_v2/hydranfc_v2_bbio_card_emulator.c
> +static void ceInitalize( void )
typo in name ceInitalize to be replaced by ceInit

2020-09-23 05:13 UTC, bvernoux commented
I see RFAL is modified (API added) please add a comment (of major modification) in file https://github.com/hydrabus/hydrafw_hydranfc_shield_v2/blob/master/src/hydranfc_v2/rfal/STSW-ST25RFAL002.txt
Note: I plan to fix build warning too (before to release v0.3)

2020-09-23 21:57 UTC, gvinet commented
* Remarks taken into account
* hydranfc_v2_bbio_card_emulator.X aim is to emulate a card, but not in stand alone mode: the response is chosen by the terminal connected to the hydra. This is why it is not in the same file as hydranfc_v2_bbio_c.X.

2020-09-24 07:12 UTC, bvernoux approved these changes

2020-09-24 07:12 UTC, merged